name: Terraform Apply
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  TF_VAR_AWS_KEY_PUB: ${{secrets.TF_VAR_AWS_KEY_PUB}}
  TF_VAR_AZURE_KEY_PUB: ${{secrets.TF_VAR_AZURE_KEY_PUB}}

jobs:
  apply_azure:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"
    - name: Terraform Apply VPN
      run: |
        terraform init
        terraform apply -auto-approve \
          -var-file="vpn.auto.tfvars" \
      working-directory: environments/dev/azure